# Generated by Django 5.2.5 on 2025-08-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_fooditem_orderitem_food_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='cook_time_minutes',
            field=models.IntegerField(default=10),
        ),
    ]
