# Generated by Django 5.2.5 on 2025-08-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_fooditem_cook_time_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cooking_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
