# Generated by Django 5.2.5 on 2025-08-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_order_cooking_started_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='cook_time_minutes',
            new_name='cook_time',
        ),
    ]
